# Function Blocks

   <div style="display: flex; align-items: center; justify-content: space-between; gap: 2em; margin-top: 1em; margin-bottom: 1em;">
     <img src="../../_static/tikz/tutorial_0/function_block_unary.svg" style="width: 30%;">
          <img src="../../_static/tikz/tutorial_0/function_block_nnary.svg" style="width: 30%;">
   </div>

Let $n,m,l \in \mathbb{N}$

A **unary operator** is a function $*:\mathbb{R}^n \to \mathbb{R}^m$ and is often symbolized with a triangle.

A **binary operator** is a function $*:\mathbb{R}^n \times \mathbb{R}^m \to \mathbb{R}^l$ and is often symbolized as a circle.

A **general operator** is a function $*:\mathbb{R}^n \times \dots \times \mathbb{R}^m \to \mathbb{R}^l \times \dots \times \mathbb{R}^k $ and its symbol changes according to context.


## Defining `FunctionBlock` Objects

In ``pykal_core``, we can instantiate one or more independent``FunctionBlock`` objects easily.

In [2]:
from pykal_core.control_system import FunctionBlock

fun_block= FunctionBlock()
fun_block.__dict__

{}

### Default Attributes

## Defining `FunctionBlock` Functions

### Unary Operators

#### Example: Gain

#### Example: Integrator

### Binary Operators

#### Example: Summation

#### Example: Switch

### General Operators

#### Example: Max

#### Example: Clip

In [26]:
import numpy as np

input = np.atleast_2d([1,-1,1]).T

In [30]:
from numpy.typing import NDArray

def multiply_vectory_by_negative_one(vector:NDArray) -> NDArray:
    return vector * -1

In [36]:
multiply_vectory_by_negative_one(input)

array([[-1],
       [ 1],
       [-1]])

In [37]:
np.negative(input)

array([[-1],
       [ 1],
       [-1]])

In [25]:
fun_block_1.invert = np.negative
fun_block_1.invert(input)

array([[-1],
       [ 1],
       [-1]])

In [33]:
r = np.atleast_2d([2,3,4])
xhat = np.atleast_2d([1,1,1])

In [34]:
def difference_between_r_and_xhat(r:NDArray,xhat:NDArray) -> NDArray:
    return r - xhat

In [35]:
difference_between_r_and_xhat(r,xhat)

array([[1, 2, 3]])

In [39]:
np.subtract(r,xhat)

array([[1, 2, 3]])

In [43]:
fun_block_2.difference = np.subtract
fun_block_2.difference(r,xhat)

array([[1, 2, 3]])

In [44]:
x1 = np.atleast_2d([1,-3,1]).T
x2 = np.atleast_2d([1,-1,1,2]).T
x3 = np.atleast_2d([1,4]).T

In [45]:
def return_vector_with_largest_euclidean_norm(*vectors):
    return max(vectors, key=lambda v: np.linalg.norm(v))

In [46]:
return_vector_with_largest_euclidean_norm(x1,x2,x3)

array([[1],
       [4]])

In [47]:
fun_block_2.largest_vector = return_vector_with_largest_euclidean_norm

In [48]:
x1 = np.atleast_2d([1,-3,1]).T
x2 = np.atleast_2d([1,-1,1,2]).T

In [49]:
def square_vectors(*vectors):
    return [np.square(v) for v in vectors]

In [52]:
square_vectors(x1,x2)

[array([[1],
        [9],
        [1]]),
 array([[1],
        [1],
        [1],
        [4]])]

[<- Signal Blocks](signal_blocks) | [Tutorials](index) | [Plant Blocks ->](plant_blocks)