# Plant Blocks

   <div style="display: flex; align-items: center; justify-content: space-between; gap: 2em; margin-top: 1em; margin-bottom: 1em;">
     <img src="../../_static/tikz/tutorial_0/plant_block_diagram.svg"  style="width: 100%;">
   </div>

We define the following sets:
- $X_p \subset \mathbb{R}^n$ is the **plant state space**
- $U_p \subset \mathbb{R}^q$ is the **plant input space**
- $T \subset \mathbb{R}$ is the **time domain**

We define the following variables:
- $x_p \in X_p$ is the **plant state**
- $u_p \in U_p$ is the **plant input**
- $t \in T$ is **time**

We define the following functions:
- $f_p: X_p \times U_p \times T \to X_p$ is the **plant dynamics function**
- $h_p: X_p \times U_p \times T \to X_p$ is the **plant output (measurements) function**

## Defining `PlantBlock` Objects

In [2]:
from pykal_core.control_system import PlantBlock

plant_block = PlantBlock(state_names=["x0","x1"]) # state names are the only required argument for the constructor

plant_block.__dict__

{'safeio': <pykal_core.utils.control_system.system_block.SafeIO at 0x712920563da0>,
 '_state_names': ['x0', 'x1'],
 '_measurement_names': ['x0_meas', 'x1_meas'],
 '_system_type': 'cti',
 '_f': <function pykal_core.control_system.PlantBlock.f_zero(xk: numpy.ndarray[tuple[typing.Any, ...], numpy.dtype[~_ScalarT]]) -> numpy.ndarray[tuple[typing.Any, ...], numpy.dtype[~_ScalarT]]>,
 '_h': <function pykal_core.control_system.PlantBlock.h_identity(xk: numpy.ndarray[tuple[typing.Any, ...], numpy.dtype[~_ScalarT]]) -> numpy.ndarray[tuple[typing.Any, ...], numpy.dtype[~_ScalarT]]>,
 '_Q': <function pykal_core.control_system.PlantBlock.make_Q.<locals>.Q() -> numpy.ndarray[tuple[typing.Any, ...], numpy.dtype[~_ScalarT]]>,
 '_R': <function pykal_core.control_system.PlantBlock.make_R.<locals>.R() -> numpy.ndarray[tuple[typing.Any, ...], numpy.dtype[~_ScalarT]]>}

### Default Attributes

Note that the `sys` object is initialized with several attributes if they are not passed explicity by the constructor (the `System.safeio` attribute is an instance of a utility class called `SafeIO` and is discussed here [link]). The default values of each attribute is described briefly in the "System Attributes" subsection. 

`sys.measurement_names` are the default measurement names, which are are just '_meas' appended to each state name

In [ ]:
sys.measurement_names

['x0_meas', 'x1_meas']

`sys.system_type` is the time structure of the dynamical system (default is "cti", or "continuous time-invariant")

In [ ]:
sys.system_types # all available system time structures for sys

{'cti', 'ctv', 'dti', 'dtv'}

`System.f_zero` is the function $f(x,u,t) = 0$, that is, our plant has zero dynamics and does not change over time.

In [ ]:
import numpy as np
xk = np.array([[1.0], [0.0]])
sys.f(xk)

array([[0.],
       [0.]])

`System.h_identity` is the function $h(x,u,t)=x$ ie the measurements are simply the state.

In [ ]:
xk = np.array([[1.0], [0.0]])
sys.h(xk)

array([[1.],
       [0.]])

`System.make_Q.<locals>.Q` is the process noise covariance $Q$ created by a factory function `System.make_Q`. The default $Q$ returns an identity matrix with noise $0.01$ on the diagonals.    

In [ ]:
sys.Q()

array([[0.01, 0.  ],
       [0.  , 0.01]])

`System.make_R.<locals>.R` is the measurement noise covariance $R$ created by a factory function `System.make_R`. The default $R$ returns an identity matrix with noise $0.01$ on the diagonals.

In [ ]:
sys.R()

array([[0.01, 0.  ],
       [0.  , 0.01]])

## Defining `PlantBlock` Functions

### Plant Dynamics 

#### Example: Linear vs Nonlinear

#### Example: Time-Varying vs Time-Invariant

### Process Noise 

#### Example: Time-Varying vs Time-Invariant

### Plant Measurements 

#### Example: Linear vs Nonlinear

#### Example: Time-Varying vs Time-Invariant

### Measurement Noise

#### Example: Time-Varying vs Time-Invariant

[<- Function Blocks](function_blocks) | [Tutorials](index) | [Detour: Abstract Functions](detour_abstract_functions) | [Observer Blocks ->](observer_blocks)